# config.yaml

# Device settings
device: "cuda:0"  # If available, otherwise CPU will be used in the script

# Path to dataset
data_paths:
  - "../pngs/"

# Training parameters
batch_size: 128  
noise_dim: 100
dim: 16  
lr: 0.0001
beta_1: 0.2
beta_2: 0.995
img_size: [128, 128, 1]
epochs: 2000  
print_every: 5000

# WandB settings
wandb:
  project: "cryoEM-WGAN-reloaded"
  architecture: "Wasserstein GAN"
  dataset: "Custom"
  run_id: 'Custom'
