# config.yaml

# Device settings
device: "cuda:2"  # If available, otherwise CPU will be used in the script

# Path to dataset
data_paths:
  - "/home/azamanos/projects/data/sim_particles/"

# Training parameters
batch_size: 64
noise_dim: 100
dim: 16  
lr: 0.0001
beta_1: 0.9
beta_2: 0.99
img_size: [128, 128, 1]
epochs: 100000
print_every: 5000
standarization: False
gaussian_filter: 0.025
critic_iterations: 5
gp_weight: 10
checkpoint_dir: 23
save_checkpoint_every: 5000
# WandB settings
wandb:
  project: "cryoEM-WGAN"
  architecture: "Wasserstein GAN_from_Zoo"
  dataset: "10K_Particles"
  run_id: '21: Zoo WGAN 100K epochs, batch_size 64 gaussian filter=0.025 normalization critic_iterations=5'
